---

- name: Install python for Ansible
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
  changed_when: False
  become: yes

- name: Esure Ansible Facts Dir exists
  file: path=/etc/ansible/facts.d state=directory recurse=yes
  become: yes
  
- name: Check for no requiretty in sudoers
  lineinfile:
   path: /etc/sudoers
   regexp: '^Defaults'
   line: 'Defaults        !requiretty'
  become: yes
  
- name: Install base packages "{{ item }}"
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-apt
    - python-dev
    - python3
    - curl
    - wget
    - net-tools
    - python-pip
    - python3-pip

- name: Install Python Dependencies
  pip: name={{ pip_packages }}
  become: yes
