# tasks file for nginx

- name: Install nginx
  package: 
    name: nginx=1.14.0-0ubuntu1.7
  become: yes

- name: Start Nginx
  systemd:
    name:
      nginx
    state:
      started
    enabled:
      yes
  become: yes