---
# tasks file for mysql-check

  - name: Make sure group mysql-check exists
    group:
      name: mysql-check
      state: present
    become: yes

  - name: Create mysql-check user
    user:
      name: mysql-check
      group: mysql-check
    become: yes

  - name: Create a directory if it doesn't exist
    file:
      path: /opt/mysql-check/{{ item }}/
      state: directory
      owner: mysql-check
      group: mysql-check
      mode: 0755
    become: yes
    with_items: 
    - bin
    - conf

  - name: Download mysql-check binary file
    get_url:
      url: https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/mysql-check/mysql-check
      dest: /opt/mysql-check/bin/mysql-check
      owner: mysql-check
      group: mysql-check
      mode: 0744
    become: yes
    notify:
      - restart mysql-check

  - name: Copying conf file with owner and permissions
    copy:
      content: "PORT={{ mysql_check_port | default('8000') }}"
      dest: /opt/mysql-check/conf/mysql-check.conf
      owner: mysql-check
      group: mysql-check
      mode: 0644
    become: yes
    notify:
      - restart mysql-check

  - name: Copying systemd file with owner and permissions
    copy:
      src: mysql-check.service
      dest: /lib/systemd/system/mysql-check.service
      mode: 0644
    become: yes
    notify:
      - restart mysql-check

  - name: Make sure a service is running and enabled 
    systemd:
      name: mysql-check.service
      state: started
      enabled: yes
      masked: no      
    become: yes
    notify:
      - mysql_check provision fact

  

  
  
